// src/types/cashfree.d.ts

/**
 * This declaration file provides typings for the Cashfree Drop-in SDK (v3).
 * It might not be exhaustive. Refer to the official Cashfree documentation for full details.
 * https://docs.cashfree.com/docs/web-drop-in-integration-3
 */

// Removed specific import as v3 is usually global
// declare module '@cashfreepayments/cashfree-js'

// Global declaration for the window.Cashfree object provided by the v3 script
declare global {
  interface Window {
    Cashfree?: CashfreeDropinSDKConstructor; // Use constructor type
  }
}

/**
 * Represents the constructor for the Cashfree Drop-in SDK instance.
 * Allows creating new instances, e.g., `new window.Cashfree()`.
 */
interface CashfreeDropinSDKConstructor {
   new (): CashfreeDropinSDKInstance; // Allows `new Cashfree()`
}

/**
 * Represents the Cashfree Drop-in SDK instance obtained after `new window.Cashfree()`.
 */
interface CashfreeDropinSDKInstance {
  /**
   * Initiates the checkout process using the Cashfree Drop-in UI.
   * @param options - The configuration options for the checkout.
   */
  drop(options: CashfreeDropinOptions): void;

  // Add other methods if you use them directly (less common with drop-in)
  // For example, if you needed to manually initialize or handle specific events:
  // initialize(options: CashfreeInitOptions): Promise<any>;
  // on(event: string, callback: (data: any) => void): void;
}


/**
 * Configuration for the Cashfree Drop-in components (v3).
 * Defines which payment methods are displayed.
 */
type CashfreeDropinComponent =
  | 'order-details' // Recommended to include first
  | 'card'
  | 'upi'
  | 'app' // Wallets (PhonePe, GPay etc. might be under UPI/App)
  | 'netbanking'
  | 'paylater'
  | 'credicardemi' // Correct spelling might be creditcardemi or similar
  | 'cardlessemi';


/**
 * Options for initiating the Cashfree Drop-in checkout (v3).
 */
export interface CashfreeDropinOptions {
  /**
   * The payment session ID obtained from your backend after creating an order.
   */
  paymentSessionId: string;
  /**
   * The unique order ID generated by your system for this transaction (must match server).
   */
  orderId: string;
  /**
   * An array specifying the payment components (methods) to display and their order.
   */
  components: CashfreeDropinComponent[];
  /**
   * Optional callback function triggered upon successful payment completion.
   * The `data` object contains details about the transaction and order.
   */
  onSuccess?: (data: CashfreeSuccessData) => void;
  /**
   * Optional callback function triggered when the payment fails or is cancelled.
   * The `data` object contains details about the order and the error.
   */
  onFailure?: (data: CashfreeFailureData) => void;
   /**
    * Optional callback triggered when specific events occur within the drop-in.
    * Example: 'checkout' when the modal opens, 'paymentSelect' when method is chosen.
    */
   // onNote?: (event: string, data: any) => void;
   /**
    * Optional: Style customization for the drop-in modal.
    */
   // style?: {
   //   backgroundColor?: string;
   //   color?: string;
   //   fontFamily?: string;
   //   fontSize?: string;
   //   errorColor?: string;
   //   theme?: 'light' | 'dark'; // Or specific theme name if supported
   // };
}

/**
 * Represents the structure of the data passed to the onSuccess callback (v3).
 * Structure might vary slightly, check console logs for exact fields.
 */
interface CashfreeSuccessData {
  order: {
    orderId: string;
    orderAmount: number;
    orderCurrency: string;
    /** Status like "PAID" */
    status: string;
    paymentSessionId: string;
    [key: string]: any; // Allow other properties returned by Cashfree
  };
  transaction?: { // Transaction details might be nested differently or partially present
    transactionId?: string;
    paymentMethod?: string; // e.g., "upi", "card"
    transactionAmount?: number;
    transactionTime?: string; // ISO Format timestamp
    transactionStatus?: string; // "SUCCESS"
    utr?: string; // For UPI
    referenceId?: string; // Bank reference
    [key: string]: any;
  };
  payment?: { // Sometimes payment details are here
     instrument?: { type: string; [key: string]: any; };
     [key: string]: any;
  }
  [key: string]: any;
}

/**
 * Represents the structure of the data passed to the onFailure callback (v3).
 * Structure might vary slightly, check console logs for exact fields.
 */
interface CashfreeFailureData {
   order: {
    orderId: string;
    orderAmount: number;
    orderCurrency: string;
    /** Status like "ACTIVE", "PAYMENT_FAILED", "USER_DROPPED", etc. */
    status: string;
    paymentSessionId?: string;
    /** Text description of the error */
    errorText?: string;
    [key: string]: any;
  };
  transaction?: { // Transaction details might be absent or incomplete
    transactionId?: string;
    paymentMethod?: string;
    transactionAmount?: number;
    transactionTime?: string;
    transactionStatus?: string; // Usually "FAILED" or similar
    [key: string]: any;
  };
  [key: string]: any;
}

// If using manual initialization separately (less common with drop-in 'drop' method)
// interface CashfreeInitOptions {
//   paymentSessionId: string;
//   orderId: string;
//   mode: 'sandbox' | 'production';
// }
