// src/types/cashfree.d.ts

/**
 * This declaration file provides basic typings for the cashfree-pg-sdk-javascript.
 * It might not be exhaustive. Refer to the official Cashfree documentation for full details.
 */

declare module 'cashfree-pg-sdk-javascript' {
  /**
   * Configuration options for initializing the Cashfree SDK.
   */
  interface CashfreeConfig {
    /**
     * The environment mode. Use 'sandbox' for testing and 'production' for live transactions.
     */
    mode: 'sandbox' | 'production';
  }

  /**
   * Options for the checkout process.
   */
  interface CheckoutOptions {
    /**
     * The payment session ID obtained from your backend after creating an order.
     */
    paymentSessionId: string;
    /**
     * The unique order ID generated by your system for this transaction.
     */
    orderId: string;
    /**
     * Optional: Configuration for displaying the checkout UI.
     */
    display?: {
      /** Show a backdrop behind the payment modal. Default: true */
      backdrop?: boolean;
      /** Hide the default Cashfree icon. Default: false */
      hideIcon?: boolean;
      /** Set the view mode. 'modal' or 'redirect'. Default: 'modal' */
      view?: 'modal' | 'redirect';
    };
     /**
     * Optional: Style customization for the checkout modal.
     */
     style?: {
       /** Background color (hex code). */
       backgroundColor?: string;
       /** Primary theme color (hex code). */
       color?: string;
       /** Font family. */
       fontFamily?: string;
       /** Font size (e.g., '14px'). */
       fontSize?: string;
       /** Error text color (hex code). */
       errorColor?: string;
       /** Theme ('light' or 'dark'). Default: 'light' */
       theme?: 'light' | 'dark';
     };
  }

  /**
   * Represents the Cashfree SDK instance.
   */
  interface CashfreeInstance {
    /**
     * Initiates the checkout process using the Cashfree Drop-in UI.
     * @param options - The configuration options for the checkout.
     */
    checkout(options: CheckoutOptions): void;

    /**
     * Optional: Allows subscribing to payment events.
     * @param eventName - The name of the event (e.g., 'paymentResponse', 'verifyPayment').
     * @param callback - The function to call when the event occurs.
     */
    // on(eventName: string, callback: (data: any) => void): void;
    // Note: Event handling might require more specific typings based on official docs.
  }

  /**
   * Loads and initializes the Cashfree SDK asynchronously.
   * @param config - The configuration object specifying the mode ('sandbox' or 'production').
   * @returns A promise that resolves with the initialized Cashfree SDK instance.
   */
  export function load(config: CashfreeConfig): Promise<CashfreeInstance>;
}
