// src/types/cashfree.d.ts

/**
 * This declaration file provides basic typings for the Cashfree Drop-in SDK (v3).
 * It might not be exhaustive. Refer to the official Cashfree documentation for full details.
 * https://docs.cashfree.com/docs/web-drop-in-integration
 */

declare module '@cashfreepayments/cashfree-js' {
  // This specific import path might not be correct for v3 drop-in.
  // The v3 drop-in SDK is typically accessed via the global window.Cashfree object
  // after its script has loaded. We'll use a global declaration instead.
  // Exporting an empty object to satisfy module resolution if needed by imports.
  const cashfreeJsModule: {};
  export default cashfreeJsModule;
}

// Global declaration for the window.Cashfree object provided by the v3 script
declare global {
  interface Window {
    Cashfree?: CashfreeDropinSDKInstance;
  }
}

/**
 * Configuration for the Cashfree Drop-in components.
 * Defines which payment methods are displayed.
 */
type CashfreeDropinComponent =
  | 'order-details'
  | 'card'
  | 'upi'
  | 'app' // Wallets
  | 'netbanking'
  | 'paylater'
  | 'credicardemi'
  | 'cardlessemi';


/**
 * Options for initiating the Cashfree Drop-in checkout.
 */
interface CashfreeDropinOptions {
  /**
   * The payment session ID obtained from your backend after creating an order.
   */
  paymentSessionId: string;
  /**
   * The unique order ID generated by your system for this transaction.
   */
  orderId: string;
  /**
   * An array specifying the payment components (methods) to display and their order.
   */
  components: CashfreeDropinComponent[];
  /**
   * Optional callback function triggered upon successful payment completion.
   * The `data` object contains details about the transaction and order.
   */
  onSuccess?: (data: CashfreeSuccessData) => void;
  /**
   * Optional callback function triggered when the payment fails or is cancelled.
   * The `data` object contains details about the order and the error.
   */
  onFailure?: (data: CashfreeFailureData) => void;
   /**
   * Optional: Set the view mode. 'modal' or 'redirect'. Default: 'modal'
   * Note: 'redirect' might not be fully supported or behave differently in v3 drop-in.
   */
   // display?: { view?: 'modal' | 'redirect' };
}

/**
 * Represents the structure of the data passed to the onSuccess callback.
 */
interface CashfreeSuccessData {
  order: {
    orderId: string;
    orderAmount: number;
    orderCurrency: string;
    /** Status like "PAID", "PENDING", etc. */
    status: string;
    paymentSessionId: string;
    [key: string]: any; // Allow other properties
  };
  transaction: {
    transactionId: string;
    paymentMethod: string;
    transactionAmount: number;
    transactionTime: string;
    transactionStatus: string; // "SUCCESS", "PENDING", "FAILED"
    [key: string]: any; // Allow other properties
  };
  [key: string]: any; // Allow other properties
}

/**
 * Represents the structure of the data passed to the onFailure callback.
 */
interface CashfreeFailureData {
   order: {
    orderId: string;
    orderAmount: number;
    orderCurrency: string;
    /** Status like "ACTIVE", "PAYMENT_FAILED", etc. */
    status: string;
    paymentSessionId?: string; // May not always be present on failure
    /** Text description of the error */
    errorText?: string;
    [key: string]: any; // Allow other properties
  };
  transaction?: { // Transaction details might be absent or incomplete on failure
    transactionId?: string;
    paymentMethod?: string;
    transactionAmount?: number;
    transactionTime?: string;
    transactionStatus?: string; // Usually "FAILED"
    [key: string]: any; // Allow other properties
  };
  [key: string]: any; // Allow other properties
}


/**
 * Represents the Cashfree Drop-in SDK instance available globally via `window.Cashfree`.
 */
interface CashfreeDropinSDKInstance {
  /**
   * Initiates the checkout process using the Cashfree Drop-in UI.
   * @param options - The configuration options for the checkout.
   */
  drop(options: CashfreeDropinOptions): void;

  // v3 might have other methods, add them here if needed based on documentation.
  // Example: methods for specific payment types if not using drop-in.
  // pay(method: string, options: any): void;
}
